services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/rails
    env_file:
      - .env
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres:17.0-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'
